# Generated by Django 3.2.3 on 2021-07-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0002_auto_20210724_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='org_name',
            new_name='desription',
        ),
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='user_create',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_create', to='membership_app.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to='membership_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='memeber', to='membership_app.member'),
            preserve_default=False,
        ),
    ]
