# Generated by Django 3.2.3 on 2021-07-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0004_auto_20210724_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='members', to='membership_app.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_create', to='membership_app.user'),
        ),
    ]
