# Generated by Django 3.2.3 on 2021-07-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0005_auto_20210724_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
