# Generated by Django 3.2.3 on 2021-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0007_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_create',
        ),
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='groups', to='membership_app.User'),
        ),
    ]
