# Generated by Django 3.2.3 on 2021-07-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0009_group_user_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='desription',
            new_name='description',
        ),
    ]
