# Generated by Django 3.2.3 on 2021-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0011_auto_20210724_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='users',
            field=models.IntegerField(),
        ),
    ]
